#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rospkg
Version  : 1.2.7
Release  : 19
URL      : https://files.pythonhosted.org/packages/b1/ea/6acf5994a7c4220e428e16778e7b71e0e42fd7d357d723aa23ff1070a5af/rospkg-1.2.7.tar.gz
Source0  : https://files.pythonhosted.org/packages/b1/ea/6acf5994a7c4220e428e16778e7b71e0e42fd7d357d723aa23ff1070a5af/rospkg-1.2.7.tar.gz
Summary  : ROS package library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: rospkg-bin = %{version}-%{release}
Requires: rospkg-python = %{version}-%{release}
Requires: rospkg-python3 = %{version}-%{release}
Requires: PyYAML
Requires: catkin_pkg
Requires: distro
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : catkin_pkg
BuildRequires : distro

%description


%package bin
Summary: bin components for the rospkg package.
Group: Binaries

%description bin
bin components for the rospkg package.


%package python
Summary: python components for the rospkg package.
Group: Default
Requires: rospkg-python3 = %{version}-%{release}

%description python
python components for the rospkg package.


%package python3
Summary: python3 components for the rospkg package.
Group: Default
Requires: python3-core
Provides: pypi(rospkg)
Requires: pypi(catkin_pkg)
Requires: pypi(distro)
Requires: pypi(pyyaml)

%description python3
python3 components for the rospkg package.


%prep
%setup -q -n rospkg-1.2.7
cd %{_builddir}/rospkg-1.2.7

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1592868150
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rosversion

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
