#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rospkg
Version  : 1.2.2
Release  : 12
URL      : https://files.pythonhosted.org/packages/b4/ad/880569a2d2c81edda85a3a1a5653aece0e30ae1db74062191dc97855248d/rospkg-1.2.2.tar.gz
Source0  : https://files.pythonhosted.org/packages/b4/ad/880569a2d2c81edda85a3a1a5653aece0e30ae1db74062191dc97855248d/rospkg-1.2.2.tar.gz
Summary  : ROS package library
Group    : Development/Tools
License  : BSD-3-Clause
Requires: rospkg-bin = %{version}-%{release}
Requires: rospkg-python = %{version}-%{release}
Requires: rospkg-python3 = %{version}-%{release}
Requires: PyYAML
Requires: catkin_pkg
Requires: distro
BuildRequires : PyYAML
BuildRequires : buildreq-distutils3
BuildRequires : catkin_pkg
BuildRequires : distro

%description
rospkg
-----
Standalone Python library for the ROS package system.
[ROS Packages Users/Developers Guide](http://docs.ros.org/independent/api/rospkg/html/)

%package bin
Summary: bin components for the rospkg package.
Group: Binaries

%description bin
bin components for the rospkg package.


%package python
Summary: python components for the rospkg package.
Group: Default
Requires: rospkg-python3 = %{version}-%{release}

%description python
python components for the rospkg package.


%package python3
Summary: python3 components for the rospkg package.
Group: Default
Requires: python3-core

%description python3
python3 components for the rospkg package.


%prep
%setup -q -n rospkg-1.2.2
cd %{_builddir}/rospkg-1.2.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1576531578
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/rosversion

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
